### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by TheWiresharkGuy** [JoeSz/Exopite-Anti-Spam#1]
Hello,

I would like to translate the captcha text into French for my own use but I am not a PHP developer.

Can you tell me how to proceed?

I would be happy to help.

**Comment by JoeSz** [comment]
Hi, I will, take a little time, I have a lot to do at work.

**Comment by JoeSz** [comment]
Hi, I have generated the pot file.
You could download POEdit (https://poeditor.com/) or Easy PO (http://www.eazypo.ca/), then load the pot file, create a translation file, then translate the English words.
