### ISSUE TITLE
language Pot File for translation is not aviable

### ISSUE THREAD

**Issue by Ricco-S** [JoeSz/Exopite-Anti-Spam#2]
Invalid POT file: exopite-anti-spam.pot

please add Translation to German

**Comment by JoeSz** [comment]
Yes, the pot file is 0 byte. I need to generate it. Or you can do it too:
https://wordpress.stackexchange.com/questions/149212/how-to-create-pot-files-with-poedit/149213#149213
http://www.eazypo.ca/

If you want to wait for me, it will take a little time, I have lot to do in my work.

**Comment by JoeSz** [comment]
But I will not translate to German. Not at the moment, at least. You could do it, after I generated the pot file, if you want to.

**Comment by JoeSz** [comment]
My German is not good enough for it, I'm afraid :S

**Comment by Ricco-S** [comment]
Hi, if you can create the Pot File, i can do it for you.

For Me 
I have changed the Plugin Files for form output to Display messages in german (image captcha and error messages)
😉

**Comment by JoeSz** [comment]
Hi, I have generated the pot file. Please let me know, if something not working :)
